### ISSUE TITLE
Chat component functionality

### ISSUE THREAD

**Issue by fabian-hanso** [fabian-hanso/capstone-project#14]
### Value Statement

As a student I would like to be able to send messages.

### Acceptance Criteria

- [ ] Component sends messages

###Subtasks

- [ ] connect to database
- [ ] write add statement
