### ISSUE TITLE
Chat - Firebase connection

### ISSUE THREAD

**Issue by fabian-hanso** [fabian-hanso/capstone-project#16]
### Value Statement

As a student I would like to see all latest messages without reloading the application.

### Acceptance Criteria

- [ ] Component re-renders automatically if the backend detects changes
- [ ] New Messages will be rendered the right way (sent / received)

###Subtasks

- [ ] write Snapshot functionality (Socket)
