### ISSUE TITLE
Create login form

### ISSUE THREAD

**Issue by fabian-hanso** [fabian-hanso/capstone-project#2]
## Value statement

As a student
I need a login form so that I can login with my username into the app

## Acceptance Criteria

- [ ]  A form with name & submit button
- [ ]  Accessibility
- [ ]  Save state in App.js

## Subtasks

- [ ]  Create new component
- [ ]  Create new branch
- [ ]  Create Name Input
- [ ]  Create Submit Button
- [ ]  Add Styling
- [ ]  write tests

## Complexitiy

low
